# https://mcr.microsoft.com/v2/vscode/devcontainers/go/tags/list
FROM mcr.microsoft.com/devcontainers/go:1-1.24-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends make curl && rm -rf /var/lib/apt/lists/*
